### ISSUE TITLE
Create new release 

### ISSUE THREAD

**Issue by m-markovic** [TEC-Toolkit/PECO#6]
Can you please double check the current version of the ontology in the development folder and create a new release?

**Comment by inaja** [comment]
Created new release based on yesterday's new peco commit. 
Someone please edit the redirect for the w3id.org/peco to point to 0.0.2

**Comment by dgarijo** [comment]
Unfortunately, there are a few errors in the doc:
- Wrong link in the serialization header
- Intro is a placeholder
- External classes and properties are not clickable (I think we have not imported their definition)
- Version should be 1.0.0, not 0.0.2

**Comment by inaja** [comment]
Thanks for pointing them out, I will fix now

**Comment by inaja** [comment]
Version is "0.0.2" in the owl file, so i will edit there as well

**Comment by dgarijo** [comment]
yes pls, change it in dev and let's push 1.0.0 directly to align with ecfo

**Comment by inaja** [comment]
Corrected version info, IRI, and date in peco.owl in dev 
Generated new release 1.0.0, and made sure to add in the info and to import the definitions. (Wrong link in the serialization header is corrected).

**Comment by dgarijo** [comment]
awesome, thanks!

**Comment by dgarijo** [comment]
w3id updated. I think we just need to create the github release if we want to obtain dois.

**Comment by inaja** [comment]
Should we close this?

**Comment by dgarijo** [comment]
Did you have the time to address the final documentation issues? (definitions, adding images and logos)

**Comment by inaja** [comment]
I don't understand what you mean by image, here is what I did:
1. I created all the missing definitions for the imported classes and properties. 
2. I created https://schema.org/logo and linked it to https://raw.githubusercontent.com/TEC-Toolkit/Emission-Conversion-Factors-Ontology/main/logos/Logo%20PECO.png?token=GHSAT0AAAAAACCJOK26TI4NXW45JQ27BVDGZCZHBBQ. 
3. added the other missing metadata to make FOOPS happier (link to LOV, issued, publisher, etc). More infor in  #7

**Comment by dgarijo** [comment]
Thanks.
Image = diagram of the ontology in the documentation.
Why are there 2 files in `development`? Which one is the right one?

**Comment by dgarijo** [comment]
Also, https://raw.githubusercontent.com/TEC-Toolkit/Emission-Conversion-Factors-Ontology/main/logos/Logo%20PECO.png?token=GHSAT0AAAAAACCJOK26TI4NXW45JQ27BVDGZCZHBBQ is a 404 probably because it's a private repo

**Comment by inaja** [comment]
I deleted ontology.ttl and kept peco.ttl. 
I did not add image. 
The link was working yesterday from a different browser (where i was not signed in to github).

**Comment by dgarijo** [comment]
I would copy the logos to the corresponding repos, just in case.

**Comment by inaja** [comment]
Logo has been corrected and image has been added (came with ECFO).

There is an issue I noticed and I think it is a WIDOCO bug: the data property qudt:value is correctly declared in the ontology file as 'is defined by' qudt. But, WIDOCO generates the documentation and says that it 'is defined by' peco.

**Comment by dgarijo** [comment]
Please open an issue in Widoco when you have the chance, and I will have a look.

**Comment by dgarijo** [comment]
For now let's fix by hand

**Comment by dgarijo** [comment]
I know why this happens. It's because the ontology annotation is as a "literal" instead of an ontology URI. That should fix it. I created the issue in Widoco the other day in any case

**Comment by inaja** [comment]
fixed manually 
and opened an issue in Widoco before i saw your new comment

**Comment by dgarijo** [comment]
All right, we are ready for release. Closing
